fix syntax

diff --git a/.github/workflows/app-CI.yml b/.github/workflows/app-CI.yml
--- a/.github/workflows/app-CI.yml
+++ b/.github/workflows/app-CI.yml
@@ -45,12 +45,12 @@ jobs:
         run: |
           # This is the same function f-droid uses to ensure their builds keep succeeding:
           # https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.derdilla.bloodPressureApp.yml
-         VERSION=$(sed -n -E "s/.*flutter:\s*'(.*)'/\1/p" app/pubspec.yaml)
-         if [ -z "$VERSION" ]; then
-           echo "Error: Could not find a Flutter version specified in app/pubspec.yaml."
-           exit 1
-         fi
-         echo "version=$VERSION" >> $GITHUB_OUTPUT
+          VERSION=$(sed -n -E "s/.*flutter:\s*'(.*)'/\1/p" app/pubspec.yaml)
+          if [ -z "$VERSION" ]; then
+            echo "Error: Could not find a Flutter version specified in app/pubspec.yaml."
+            exit 1
+          fi
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
         with:
